# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run PowerShell
        shell: pwsh
        run: |
         Write-Host "Running on version: $($PSVersionTable.PSVersion)"
      #- name: Install PowerShell Core
      # uses: actions/setup-powershell@v1 # Installs pwsh automatically
      - name: Run Script
        shell: pwsh
        run: Write-Host "This works now!"
      - name: Run a one-line script
        run: echo "The context workspace path is ${{ github.workspace }}"
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1
       
      - name: Build SSIS Project
        run: |
           SSISBuild.exe / \
            -p:"${{ github.workspace }}/Integration_Services_Test.dtproj"\
            -o:"${{ github.workspace }}/OutputBuild"
       

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
